package com.carrie.lianlian.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "ANN".
 */
public class Ann {

    private Long id;
    private String content;
    private String person;
    private String relationship;
    private String icon;
    private String date;
    private String remind;
    private String remark;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Ann() {
    }

    public Ann(Long id) {
        this.id = id;
    }

    public Ann(Long id, String content, String person, String relationship, String icon, String date, String remind, String remark) {
        this.id = id;
        this.content = content;
        this.person = person;
        this.relationship = relationship;
        this.icon = icon;
        this.date = date;
        this.remind = remind;
        this.remark = remark;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getPerson() {
        return person;
    }

    public void setPerson(String person) {
        this.person = person;
    }

    public String getRelationship() {
        return relationship;
    }

    public void setRelationship(String relationship) {
        this.relationship = relationship;
    }

    public String getIcon() {
        return icon;
    }

    public void setIcon(String icon) {
        this.icon = icon;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public String getRemind() {
        return remind;
    }

    public void setRemind(String remind) {
        this.remind = remind;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
