package com.carrie.lianlian.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig diaryDaoConfig;
    private final DaoConfig planDaoConfig;
    private final DaoConfig moneyDaoConfig;
    private final DaoConfig moneyClassifyDaoConfig;
    private final DaoConfig moneyAccountDaoConfig;
    private final DaoConfig annDaoConfig;
    private final DaoConfig memoDaoConfig;

    private final DiaryDao diaryDao;
    private final PlanDao planDao;
    private final MoneyDao moneyDao;
    private final MoneyClassifyDao moneyClassifyDao;
    private final MoneyAccountDao moneyAccountDao;
    private final AnnDao annDao;
    private final MemoDao memoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        diaryDaoConfig = daoConfigMap.get(DiaryDao.class).clone();
        diaryDaoConfig.initIdentityScope(type);

        planDaoConfig = daoConfigMap.get(PlanDao.class).clone();
        planDaoConfig.initIdentityScope(type);

        moneyDaoConfig = daoConfigMap.get(MoneyDao.class).clone();
        moneyDaoConfig.initIdentityScope(type);

        moneyClassifyDaoConfig = daoConfigMap.get(MoneyClassifyDao.class).clone();
        moneyClassifyDaoConfig.initIdentityScope(type);

        moneyAccountDaoConfig = daoConfigMap.get(MoneyAccountDao.class).clone();
        moneyAccountDaoConfig.initIdentityScope(type);

        annDaoConfig = daoConfigMap.get(AnnDao.class).clone();
        annDaoConfig.initIdentityScope(type);

        memoDaoConfig = daoConfigMap.get(MemoDao.class).clone();
        memoDaoConfig.initIdentityScope(type);

        diaryDao = new DiaryDao(diaryDaoConfig, this);
        planDao = new PlanDao(planDaoConfig, this);
        moneyDao = new MoneyDao(moneyDaoConfig, this);
        moneyClassifyDao = new MoneyClassifyDao(moneyClassifyDaoConfig, this);
        moneyAccountDao = new MoneyAccountDao(moneyAccountDaoConfig, this);
        annDao = new AnnDao(annDaoConfig, this);
        memoDao = new MemoDao(memoDaoConfig, this);

        registerDao(Diary.class, diaryDao);
        registerDao(Plan.class, planDao);
        registerDao(Money.class, moneyDao);
        registerDao(MoneyClassify.class, moneyClassifyDao);
        registerDao(MoneyAccount.class, moneyAccountDao);
        registerDao(Ann.class, annDao);
        registerDao(Memo.class, memoDao);
    }
    
    public void clear() {
        diaryDaoConfig.getIdentityScope().clear();
        planDaoConfig.getIdentityScope().clear();
        moneyDaoConfig.getIdentityScope().clear();
        moneyClassifyDaoConfig.getIdentityScope().clear();
        moneyAccountDaoConfig.getIdentityScope().clear();
        annDaoConfig.getIdentityScope().clear();
        memoDaoConfig.getIdentityScope().clear();
    }

    public DiaryDao getDiaryDao() {
        return diaryDao;
    }

    public PlanDao getPlanDao() {
        return planDao;
    }

    public MoneyDao getMoneyDao() {
        return moneyDao;
    }

    public MoneyClassifyDao getMoneyClassifyDao() {
        return moneyClassifyDao;
    }

    public MoneyAccountDao getMoneyAccountDao() {
        return moneyAccountDao;
    }

    public AnnDao getAnnDao() {
        return annDao;
    }

    public MemoDao getMemoDao() {
        return memoDao;
    }

}
