package com.carrie.lianlian.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import android.database.Cursor;

/**
 * Entity mapped to table "DIARY".
 */
public class Diary {

    private Long id;
    private String title;
    /** Not-null value. */
    private String content;
    /** Not-null value. */
    private String CreateDate;
    /** Not-null value. */
    private String UpdateDate;
    private String weather;
    private String mood;
    private String bg;
    private Integer textSize;
    private Integer textColor;
    private String label;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Diary() {
    }

    public Diary(Long id) {
        this.id = id;
    }

    public Diary(Long id, String title, String content, String CreateDate, String UpdateDate, String weather, String mood, String bg, Integer textSize, Integer textColor, String label) {
        this.id = id;
        this.title = title;
        this.content = content;
        this.CreateDate = CreateDate;
        this.UpdateDate = UpdateDate;
        this.weather = weather;
        this.mood = mood;
        this.bg = bg;
        this.textSize = textSize;
        this.textColor = textColor;
        this.label = label;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    /** Not-null value. */
    public String getContent() {
        return content;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setContent(String content) {
        this.content = content;
    }

    /** Not-null value. */
    public String getCreateDate() {
        return CreateDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCreateDate(String CreateDate) {
        this.CreateDate = CreateDate;
    }

    /** Not-null value. */
    public String getUpdateDate() {
        return UpdateDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUpdateDate(String UpdateDate) {
        this.UpdateDate = UpdateDate;
    }

    public String getWeather() {
        return weather;
    }

    public void setWeather(String weather) {
        this.weather = weather;
    }

    public String getMood() {
        return mood;
    }

    public void setMood(String mood) {
        this.mood = mood;
    }

    public String getBg() {
        return bg;
    }

    public void setBg(String bg) {
        this.bg = bg;
    }

    public Integer getTextSize() {
        return textSize;
    }

    public void setTextSize(Integer textSize) {
        this.textSize = textSize;
    }

    public Integer getTextColor() {
        return textColor;
    }

    public void setTextColor(Integer textColor) {
        this.textColor = textColor;
    }

    public String getLabel() {
        return label;
    }

    public void setLabel(String label) {
        this.label = label;
    }

    // KEEP METHODS - put your custom methods here
    public void setData(Cursor cursor, Diary diary){
        diary.setId(cursor.getLong(cursor.getColumnIndex("_id")));
        diary.setTitle( cursor.getString(cursor.getColumnIndex("TITLE")));
        diary.setContent(cursor.getString(cursor.getColumnIndex("CONTENT")));
        diary.setCreateDate(cursor.getString(cursor.getColumnIndex("CREATE_DATE")));
        diary.setUpdateDate(cursor.getString(cursor.getColumnIndex("UPDATE_DATE")));
        diary.setWeather(cursor.getString(cursor.getColumnIndex("WEATHER")));
        diary.setMood(cursor.getString(cursor.getColumnIndex("MOOD")));
        diary.setBg(cursor.getString(cursor.getColumnIndex("BG")));
        diary.setTextSize(cursor.getInt(cursor.getColumnIndex("TEXT_SIZE")));
        diary.setTextColor(cursor.getInt(cursor.getColumnIndex("TEXT_COLOR")));
        diary.setLabel(cursor.getString(cursor.getColumnIndex("LABEL")));
    }

    @Override
    public String toString() {
        return "Diary{" +
                "id=" + id +
                ", title='" + title + '\'' +
                ", content='" + content + '\'' +
                ", CreateDate='" + CreateDate + '\'' +
                ", UpdateDate='" + UpdateDate + '\'' +
                ", weather=" + weather +
                ", mood=" + mood +
                ", bg='" + bg + '\'' +
                ", textSize=" + textSize +
                ", textColor=" + textColor +
                '}';
    }
    // KEEP METHODS END

}
