package com.carrie.lianlian.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "MEMO".
 */
public class Memo {

    private String content;
    private String date;
    private String bg;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Memo() {
    }

    public Memo(String content, String date, String bg) {
        this.content = content;
        this.date = date;
        this.bg = bg;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public String getBg() {
        return bg;
    }

    public void setBg(String bg) {
        this.bg = bg;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
