package com.carrie.lianlian.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MONEY_ACCOUNT".
*/
public class MoneyAccountDao extends AbstractDao<MoneyAccount, String> {

    public static final String TABLENAME = "MONEY_ACCOUNT";

    /**
     * Properties of entity MoneyAccount.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Icon = new Property(0, String.class, "icon", false, "ICON");
        public final static Property Name = new Property(1, String.class, "name", true, "NAME");
        public final static Property Balance = new Property(2, String.class, "balance", false, "BALANCE");
    };


    public MoneyAccountDao(DaoConfig config) {
        super(config);
    }
    
    public MoneyAccountDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MONEY_ACCOUNT\" (" + //
                "\"ICON\" TEXT," + // 0: icon
                "\"NAME\" TEXT PRIMARY KEY NOT NULL ," + // 1: name
                "\"BALANCE\" TEXT);"); // 2: balance
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MONEY_ACCOUNT\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, MoneyAccount entity) {
        stmt.clearBindings();
 
        String icon = entity.getIcon();
        if (icon != null) {
            stmt.bindString(1, icon);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String balance = entity.getBalance();
        if (balance != null) {
            stmt.bindString(3, balance);
        }
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1);
    }    

    /** @inheritdoc */
    @Override
    public MoneyAccount readEntity(Cursor cursor, int offset) {
        MoneyAccount entity = new MoneyAccount( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // icon
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // balance
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, MoneyAccount entity, int offset) {
        entity.setIcon(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setBalance(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(MoneyAccount entity, long rowId) {
        return entity.getName();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(MoneyAccount entity) {
        if(entity != null) {
            return entity.getName();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
