package com.carrie.lianlian.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "MONEY".
 */
public class Money implements java.io.Serializable {

    private Long id;
    /** Not-null value. */
    private String classifyIcon;
    /** Not-null value. */
    private String accountIcon;
    /** Not-null value. */
    private String classify;
    /** Not-null value. */
    private String account;
    /** Not-null value. */
    private String content;
    private String income;
    private String expense;
    private String price;
    private int state;
    /** Not-null value. */
    private String date;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Money() {
    }

    public Money(Long id) {
        this.id = id;
    }

    public Money(Long id, String classifyIcon, String accountIcon, String classify, String account, String content, String income, String expense, String price, int state, String date) {
        this.id = id;
        this.classifyIcon = classifyIcon;
        this.accountIcon = accountIcon;
        this.classify = classify;
        this.account = account;
        this.content = content;
        this.income = income;
        this.expense = expense;
        this.price = price;
        this.state = state;
        this.date = date;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getClassifyIcon() {
        return classifyIcon;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setClassifyIcon(String classifyIcon) {
        this.classifyIcon = classifyIcon;
    }

    /** Not-null value. */
    public String getAccountIcon() {
        return accountIcon;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAccountIcon(String accountIcon) {
        this.accountIcon = accountIcon;
    }

    /** Not-null value. */
    public String getClassify() {
        return classify;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setClassify(String classify) {
        this.classify = classify;
    }

    /** Not-null value. */
    public String getAccount() {
        return account;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAccount(String account) {
        this.account = account;
    }

    /** Not-null value. */
    public String getContent() {
        return content;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setContent(String content) {
        this.content = content;
    }

    public String getIncome() {
        return income;
    }

    public void setIncome(String income) {
        this.income = income;
    }

    public String getExpense() {
        return expense;
    }

    public void setExpense(String expense) {
        this.expense = expense;
    }

    public String getPrice() {
        return price;
    }

    public void setPrice(String price) {
        this.price = price;
    }

    public int getState() {
        return state;
    }

    public void setState(int state) {
        this.state = state;
    }

    /** Not-null value. */
    public String getDate() {
        return date;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDate(String date) {
        this.date = date;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
