package com.carrie.lianlian.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "MONEY_ACCOUNT".
 */
public class MoneyAccount {

    private String icon;
    private String name;
    private String balance;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public MoneyAccount() {
    }

    public MoneyAccount(String name) {
        this.name = name;
    }

    public MoneyAccount(String icon, String name, String balance) {
        this.icon = icon;
        this.name = name;
        this.balance = balance;
    }

    public String getIcon() {
        return icon;
    }

    public void setIcon(String icon) {
        this.icon = icon;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getBalance() {
        return balance;
    }

    public void setBalance(String balance) {
        this.balance = balance;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
