package com.carrie.lianlian.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "PLAN".
 */
public class Plan implements java.io.Serializable {

    private Long id;
    private String importantDegree;
    private Integer icon;
    /** Not-null value. */
    private String content;
    private boolean finish;
    private boolean remind;
    /** Not-null value. */
    private String date;
    private String startTime;
    private String endTime;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Plan() {
    }

    public Plan(Long id) {
        this.id = id;
    }

    public Plan(Long id, String importantDegree, Integer icon, String content, boolean finish, boolean remind, String date, String startTime, String endTime) {
        this.id = id;
        this.importantDegree = importantDegree;
        this.icon = icon;
        this.content = content;
        this.finish = finish;
        this.remind = remind;
        this.date = date;
        this.startTime = startTime;
        this.endTime = endTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getImportantDegree() {
        return importantDegree;
    }

    public void setImportantDegree(String importantDegree) {
        this.importantDegree = importantDegree;
    }

    public Integer getIcon() {
        return icon;
    }

    public void setIcon(Integer icon) {
        this.icon = icon;
    }

    /** Not-null value. */
    public String getContent() {
        return content;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setContent(String content) {
        this.content = content;
    }

    public boolean getFinish() {
        return finish;
    }

    public void setFinish(boolean finish) {
        this.finish = finish;
    }

    public boolean getRemind() {
        return remind;
    }

    public void setRemind(boolean remind) {
        this.remind = remind;
    }

    /** Not-null value. */
    public String getDate() {
        return date;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDate(String date) {
        this.date = date;
    }

    public String getStartTime() {
        return startTime;
    }

    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }

    public String getEndTime() {
        return endTime;
    }

    public void setEndTime(String endTime) {
        this.endTime = endTime;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
